drvAsynSerialPortConfigure ("$(COM1)", "/dev/ttyUSB0")
asynOctetSetInputEos ("$(COM1)",0,"\r\n")
asynOctetSetOutputEos ("$(COM1)",0,"\r\n")
asynSetOption ("$(COM1)", 0, "baud", "230400")
asynSetOption ("$(COM1)", 0, "bits", "8")
asynSetOption ("$(COM1)", 0, "parity", "none")
asynSetOption ("$(COM1)", 0, "stop", "1")

dbLoadRecords("detector_controls.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), SYNC_EVNT=16, TSU-OFF=50, CLK_RST_EVNT=15, TSL-OFF=51, EVR=EVR-01, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=0, REG=LPBK, DESC=loopback test register, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=1, SCAN=Passive, REG=GIT, DESC=git hash, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=2, REG=BUILD, DESC=build time, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=3, SCAN=Passive, REG=ID-L, DESC=device ID_L, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=4, SCAN=Passive, REG=ID-M, DESC=device ID_M, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=5, SCAN=Passive, REG=ID-H, DESC=device ID_H, PRO=ics-dg.proto")
dbLoadRecords("reset_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=6, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=7, REG=ADC-SEL, DESC=ADC channel select, PRO=ics-dg.proto")
dbLoadRecords("oversampling.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=8, PRO=ics-dg.proto")
dbLoadRecords("sampling_mode.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=9, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=10, REG=CH1-T, DESC=ADC Ch1 Threshold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=11, REG=CH2-T, DESC=ADC Ch2 Threshold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=12, REG=CH3-T, DESC=ADC Ch3 Threshold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=13, REG=CH4-T, DESC=ADC Ch4 Threshold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=14, REG=RH, DESC=Rising Hold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=15, REG=FH, DESC=Falling Hold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=16, REG=SMPSB, DESC=Samples Before, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=17, REG=SMPSA, DESC=Samples After, PRO=ics-dg.proto")
dbLoadRecords("rw_mac_address.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=18, DIR=SRC, PRO=ics-dg.proto")
dbLoadRecords("rw_mac_address.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=20, DIR=DST, PRO=ics-dg.proto")
dbLoadRecords("rw_ip_address.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=22, DIR=SRC, PRO=ics-dg.proto")
dbLoadRecords("rw_ip_address.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=23, DIR=DST, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=24, REG=UDPS, DESC=UDP Source Port, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=25, REG=UDPD, DESC=UDP Destination Port, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=26, REG=PTO, DESC=Packet Timeout, PRO=ics-dg.proto")
dbLoadRecords("channel_gain.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=27, CH=1, PRO=ics-dg.proto")
dbLoadRecords("channel_gain.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=28, CH=2, PRO=ics-dg.proto")
dbLoadRecords("channel_gain.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=29, CH=3, PRO=ics-dg.proto")
dbLoadRecords("channel_gain.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=30, CH=4, PRO=ics-dg.proto")
dbLoadRecords("ch_offset.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=31, CH=1, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=35, REG=I2C-ADDR, DESC=I2C address, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=36, REG=I2C-M2S, DESC=I2C M2S Data, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=37, REG=I2C-S2M, DESC=I2C S2M Data, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=38, REG=I2C-ENA, DESC=I2C Ena, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=39, REG=LEDSEL, DESC=LED select, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=40, REG=PKCNT, DESC=Packet Count, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=41, REG=CH1-BFOV, DESC=Ch 1 Buff Overflow Cnt, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=42, REG=CH2-BFOV, DESC=Ch 2 Buff Overflow Cnt, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=43, REG=CH3-BFOV, DESC=Ch 3 Buff Overflow Cnt, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=44, REG=CH4-BFOV, DESC=Ch 4 Buff Overflow Cnt, PRO=ics-dg.proto")
dbLoadRecords("ro_2x16bit_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=45, NR2=2, NR1=1, REG=SNAP, DESC=ADC snap value ch, PRO=ics-dg.proto")
dbLoadRecords("ro_2x16bit_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=46, NR2=4, NR1=3, REG=SNAP, DESC=ADC snap value ch, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=47, SCAN=10 second, REG=STATUS0, DESC=Status 0, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=48, SCAN=10 second, REG=STATUS1, DESC=Status 1, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=49, REG=STATUS2, DESC=Status 2, PRO=ics-dg.proto")
dbLoadRecords("clock_select.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=52, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=53, REG=TST-PKT-SEL, DESC=Test packet select, PRO=ics-dg.proto")
dbLoadRecords("payload_select.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=54, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=55, REG=TST-PUL-ENA, DESC=Test pulse enable, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=56, REG=CH1-TST-W, DESC=Ch1 Test pulse width, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=57, REG=CH2-TST-W, DESC=Ch2 Test pulse width, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=58, REG=CH3-TST-W, DESC=Ch3 Test pulse width, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=59, REG=CH4-TST-W, DESC=Ch4 Test pulse width, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=60, REG=CH1-TST-GP, DESC=Ch1 tst pulse gap, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=61, REG=CH2-TST-GP, DESC=Ch2 tst pulse gap, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=62, REG=CH3-TST-GP, DESC=Ch3 tst pulse gap, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=63, REG=CH4-TST-GP, DESC=Ch4 tst pulse gap, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=64, REG=CH1-TST-CNT, DESC=Ch1 tst pulse gen cnt, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=65, REG=CH2-TST-CNT, DESC=Ch2 tst pulse gen cnt, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=66, REG=CH3-TST-CNT, DESC=Ch3 tst pulse gen cnt, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=67, REG=CH4-TST-CNT, DESC=Ch4 tst pulse gen cnt, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=68, REG=CH1-TST-BUF, DESC=Ch1 tst pulse gen buf, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=69, REG=CH2-TST-BUF, DESC=Ch2 tst pulse gen buf, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=70, REG=CH3-TST-BUF, DESC=Ch3 tst pulse gen buf, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV1), COM=$(COM1), OFF=71, REG=CH4-TST-BUF, DESC=Ch4 tst pulse gen buf, PRO=ics-dg.proto")


drvAsynSerialPortConfigure ("$(COM2)", "/dev/ttyUSB1")
asynOctetSetInputEos ("$(COM2)",0,"\r\n")
asynOctetSetOutputEos ("$(COM2)",0,"\r\n")
asynSetOption ("$(COM2)", 0, "baud", "230400")
asynSetOption ("$(COM2)", 0, "bits", "8")
asynSetOption ("$(COM2)", 0, "parity", "none")
asynSetOption ("$(COM2)", 0, "stop", "1")

dbLoadRecords("detector_controls.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), SYNC_EVNT=16, TSU-OFF=50, CLK_RST_EVNT=15, TSL-OFF=51, EVR=EVR-01, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=0, REG=LPBK, DESC=loopback test register, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=1, SCAN=Passive, REG=GIT, DESC=git hash, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=2, REG=BUILD, DESC=build time, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=3, SCAN=Passive, REG=ID-L, DESC=device ID_L, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=4, SCAN=Passive, REG=ID-M, DESC=device ID_M, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=5, SCAN=Passive, REG=ID-H, DESC=device ID_H, PRO=ics-dg.proto")
dbLoadRecords("reset_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=6, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=7, REG=ADC-SEL, DESC=ADC channel select, PRO=ics-dg.proto")
dbLoadRecords("oversampling.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=8, PRO=ics-dg.proto")
dbLoadRecords("sampling_mode.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=9, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=10, REG=CH1-T, DESC=ADC Ch1 Threshold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=11, REG=CH2-T, DESC=ADC Ch2 Threshold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=12, REG=CH3-T, DESC=ADC Ch3 Threshold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=13, REG=CH4-T, DESC=ADC Ch4 Threshold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=14, REG=RH, DESC=Rising Hold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=15, REG=FH, DESC=Falling Hold, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=16, REG=SMPSB, DESC=Samples Before, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=17, REG=SMPSA, DESC=Samples After, PRO=ics-dg.proto")
dbLoadRecords("rw_mac_address.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=18, DIR=SRC, PRO=ics-dg.proto")
dbLoadRecords("rw_mac_address.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=20, DIR=DST, PRO=ics-dg.proto")
dbLoadRecords("rw_ip_address.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=22, DIR=SRC, PRO=ics-dg.proto")
dbLoadRecords("rw_ip_address.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=23, DIR=DST, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=24, REG=UDPS, DESC=UDP Source Port, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=25, REG=UDPD, DESC=UDP Destination Port, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=26, REG=PTO, DESC=Packet Timeout, PRO=ics-dg.proto")
dbLoadRecords("channel_gain.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=27, CH=1, PRO=ics-dg.proto")
dbLoadRecords("channel_gain.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=28, CH=2, PRO=ics-dg.proto")
dbLoadRecords("channel_gain.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=29, CH=3, PRO=ics-dg.proto")
dbLoadRecords("channel_gain.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=30, CH=4, PRO=ics-dg.proto")
dbLoadRecords("ch_offset.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=31, CH=1, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=35, REG=I2C-ADDR, DESC=I2C address, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=36, REG=I2C-M2S, DESC=I2C M2S Data, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=37, REG=I2C-S2M, DESC=I2C S2M Data, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=38, REG=I2C-ENA, DESC=I2C Ena, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=39, REG=LEDSEL, DESC=LED select, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=40, REG=PKCNT, DESC=Packet Count, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=41, REG=CH1-BFOV, DESC=Ch 1 Buff Overflow Cnt, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=42, REG=CH2-BFOV, DESC=Ch 2 Buff Overflow Cnt, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=43, REG=CH3-BFOV, DESC=Ch 3 Buff Overflow Cnt, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=44, REG=CH4-BFOV, DESC=Ch 4 Buff Overflow Cnt, PRO=ics-dg.proto")
dbLoadRecords("ro_2x16bit_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=45, NR2=2, NR1=1, REG=SNAP, DESC=ADC snap value ch, PRO=ics-dg.proto")
dbLoadRecords("ro_2x16bit_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=46, NR2=4, NR1=3, REG=SNAP, DESC=ADC snap value ch, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=47, SCAN=10 second, REG=STATUS0, DESC=Status 0, PRO=ics-dg.proto")
dbLoadRecords("ro_hex_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=48, SCAN=10 second, REG=STATUS1, DESC=Status 1, PRO=ics-dg.proto")
dbLoadRecords("ro_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=49, REG=STATUS2, DESC=Status 2, PRO=ics-dg.proto")
dbLoadRecords("clock_select.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=52, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=53, REG=TST-PKT-SEL, DESC=Test packet select, PRO=ics-dg.proto")
dbLoadRecords("payload_select.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=54, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=55, REG=TST-PUL-ENA, DESC=Test pulse enable, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=56, REG=CH1-TST-W, DESC=Ch1 Test pulse width, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=57, REG=CH2-TST-W, DESC=Ch2 Test pulse width, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=58, REG=CH3-TST-W, DESC=Ch3 Test pulse width, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=59, REG=CH4-TST-W, DESC=Ch4 Test pulse width, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=60, REG=CH1-TST-GP, DESC=Ch1 tst pulse gap, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=61, REG=CH2-TST-GP, DESC=Ch2 tst pulse gap, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=62, REG=CH3-TST-GP, DESC=Ch3 tst pulse gap, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=63, REG=CH4-TST-GP, DESC=Ch4 tst pulse gap, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=64, REG=CH1-TST-CNT, DESC=Ch1 tst pulse gen cnt, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=65, REG=CH2-TST-CNT, DESC=Ch2 tst pulse gen cnt, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=66, REG=CH3-TST-CNT, DESC=Ch3 tst pulse gen cnt, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=67, REG=CH4-TST-CNT, DESC=Ch4 tst pulse gen cnt, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=68, REG=CH1-TST-BUF, DESC=Ch1 tst pulse gen buf, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=69, REG=CH2-TST-BUF, DESC=Ch2 tst pulse gen buf, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=70, REG=CH3-TST-BUF, DESC=Ch3 tst pulse gen buf, PRO=ics-dg.proto")
dbLoadRecords("rw_register.db", "SYS=$(SYS), DEV=$(DEV2), COM=$(COM2), OFF=71, REG=CH4-TST-BUF, DESC=Ch4 tst pulse gen buf, PRO=ics-dg.proto")


dbLoadRecords("evr_detector_controls.db", "SYS=$(SYS), EVR=$(EVR), TSEVT=$(SYNC_EVNT_LETTER),SYNC_EVNT=$(SYNC_TRIG_EVT)")




